# Generated by Django 5.0.6 on 2024-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('degree', models.FloatField()),
                ('reika', models.FloatField()),
                ('rate', models.FloatField()),
                ('charge', models.FloatField()),
                ('signal', models.FloatField()),
                ('reading_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
